### ISSUE TITLE
unable to write x configuration file

### ISSUE THREAD

**Issue by Korothi** [marioroy/nvidia-driver-on-clear-linux#1]
Any attempt to add new x configuration file will stop X from working, i want to add force full composition pipeline setting because that possibly fixes refresh rate issues.

**Comment by marioroy** [comment]
How to enable force full composition pipeline.
1. Launch "NVIDIA Settings" and click on "X Server Display Configuration" in left panel.
2. Click on the "Advanced..." button and enable "Force Full Composition Pipeline" per display.
3. Click on the "Save to X Configuration File" button and save to "/tmp/xorg.conf".
4. Extract the "Screen" section from "/tmp/xorg.conf" to "/etc/X11/xorg.conf.d/nvidia-screen-opt.conf".

**Comment by marioroy** [comment]
I have three files in "/etc/X11/xorg.conf.d". Force full composition pipeline is working for me.
1. nvidia-drm-outputclass.conf
2. nvidia-files-opt.conf
3. nvidia-screen-opt.conf
