### ISSUE TITLE
Possible bug fix for HWAccel with Clear Fraction codecs-cuda

### ISSUE THREAD

**Issue by asreich** [marioroy/nvidia-driver-on-clear-linux#1]
First off, thank you so much for your hard work on this. You've made this process so much easier for everyone and I've learned so much about graphics and hardware acceleration from your work already. I know this can take a lot of time to maintain and fix and I wanted to contribute something I encountered during this process.

Background: I know very, very little about all these scripts and things you've set in scripts and what not, I understand basic shell and desktop environments but I had no idea how to actually confirm whether hardware acceleration was turned on and I only recently found out about the whole "h264 is not packaged with Firefox" thing.

**Possible bug:**

You'll have to tell me whether this is actually a bug or what's going on here, but I think [L12](https://github.com/marioroy/nvidia-driver-on-clear-linux/blob/main/HWAccel/firefox/firefox.conf#L12) of the firefox.conf (and maybe other files) needs to be updated to look more like the following or some functional equivalent:

```bash
export LD_LIBRARY_PATH=/opt/3rd-party/bundles/clearfraction/usr/local-cuda/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64
```

I have two machines which I've been using your scripts for and following the instructions. They are both on 520.61.05, Clear Linux. One has an i7-2600 (Intel® HD Graphics 2000) on the DH67CL platform with a Gigabyte GTX 980 and then an i7-5820K (no onboard graphics) on X99 with an EVGA GTX 1070. The same monitors are plugged into both systems, just flipping which uses DVI (2x) and HDMI (2x) for the primary. I decided I wanted to fix the H264 issue (not yet seeing you had added your own stuff to this repo) and I followed [this guide](https://community.clearlinux.org/t/bash-script-to-add-h-264-support-for-firefox/2367) which seemed pretty straightforward and got it working.

Once I saw that you had notes about the hardware acceleration, I switched everything out and removed the old stuff. H264 videos did not play using the firefox.conf nor the run-firefox script provided. I had to add Clear Fraction's `/usr/lib64` path as well for everything to work as expected. After that I was able to confirm with both [GreenWithEnvy](https://flathub.org/apps/details/com.leinardi.gwe) and the `about:support` page on Firefox that everything I was seeing was expected. I did also find out that my beloved GTX 980 NVENC [does not support](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) nearly as many decoding formats as I thought haha.

So yeah, let me know if I'm missing something, if there's something unique about my config or how much of an edge case this might be. Maybe this isn't an issue with newer CPUs/GPUs? I'd love to know. Thanks again for your great work!

**Comment by marioroy** [comment]
I verified HW acceleration working for me. Perhaps, my repo is broken for configurations involving Intel integrated graphics. I'm not sure. Unfortunately, I have an AMD CPU without integrated graphics. Thus, I'm unable to do further testing.

This repo has the [HWAccel](https://github.com/marioroy/nvidia-driver-on-clear-linux/tree/main/HWAccel) folder.  There are two methods for installing the relevant VA-API drivers; manual or via the 3rd-party "codecs-cuda" bundle. If choosing the latter, remember to run the `bash pre-update-driver update` command.

Check for presence of the {nvdec_drv_video.so, nvidia_drv_video.so, and vdpau_drv_video.so} VA-API drivers: 
```bash
ls -l /usr/lib64/dri
```

Ensure, you have the Firefox configuration file. From the HWAccel folder:

```bash
cp firefox/firefox.conf ~/.config/.
```

There are minimum `about:config` settings. It requires restarting Firefox for the changes to take effect.

```text
# Required, enables hardware acceleration using VA-API.
media.ffmpeg.vaapi.enabled                     true

# Disable AV1 content; Ensure false if graphics lacks AV1 support.
media.av1.enabled                              false
```

The only thing I can think of is the nvidia-drm-outputclass.conf file. Maybe, I should not add the bottom OutputClass section. This was needed for one user.

```bash
cat /etc/X11/xorg.conf.d/nvidia-drm-outputclass.conf
```
```text
Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "AllowEmptyInitialConfiguration"
    Option "PrimaryGPU" "yes"
    Option "SLI" "Auto"
    Option "BaseMosaic" "on"
EndSection

Section "OutputClass"
    Identifier "intel"
    MatchDriver "i915"
    Driver "modesetting"
EndSection
```

In closing, my repo is not compatible (but, I tried) with other repos that install NVIDIA drivers. In other words, I'm not sure if you have conflicting files; (/etc/kerne/cmdline.d/, /etc/kernel/cmdline-removal.d/, /etc/X11/xorg.conf.d/, /etc/ld.so.conf.d/, or /etc/modprobe.d/).

Remember to disable AV1 in Firefox if your graphics does not decode AV1 content.

**Comment by marioroy** [comment]
Hi again... Did you get HW acceleration working using the 3rd-party bundle? Is the reason the LD_LIBRARY_PATH needs to be set in the Firefox configuration or run script? I see, I will push an update.

**Comment by marioroy** [comment]
What do you see when you run the following ldd command?
```bash
ldd /usr/lib64/dri/nvidia_drv_video.so
```
```text
	linux-vdso.so.1 (0x00007f0b256b4000)
	libgstcodecparsers-1.0.so.0 => /usr/lib64/libgstcodecparsers-1.0.so.0 (0x00007f0b255f0000)
	libEGL.so.1 => /opt/nvidia/lib64/libEGL.so.1 (0x00007f0b25200000)
	libc.so.6 => /usr/lib64/glibc-hwcaps/x86-64-v3/libc.so.6 (0x00007f0b25001000)
	libgstbase-1.0.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libgstbase-1.0.so.0.2005.0 (0x00007f0b2553c000)
	libgstreamer-1.0.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libgstreamer-1.0.so.0.2005.0 (0x00007f0b24e58000)
	libglib-2.0.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libglib-2.0.so.0.7400.1 (0x00007f0b24cb4000)
	libm.so.6 => /usr/lib64/glibc-hwcaps/x86-64-v3/libm.so.6 (0x00007f0b2545a000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f0b25455000)
	libGLdispatch.so.0 => /opt/nvidia/lib64/libGLdispatch.so.0 (0x00007f0b24800000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f0b256b6000)
	libgobject-2.0.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libgobject-2.0.so.0.7400.1 (0x00007f0b24c30000)
	libgmodule-2.0.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libgmodule-2.0.so.0.7400.1 (0x00007f0b25440000)
	libpcre2-8.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libpcre2-8.so.0.10.2 (0x00007f0b24b74000)
	libffi.so.7 => /usr/lib64/libffi.so.7 (0x00007f0b25433000)
```

**Comment by asreich** [comment]
In reply to your first comment, I have the same problem with both Intel processes. The i7-2600 has integrated graphics but the i7-5820K does not, and no cables are plugged into the motherboard video ports so I don't think this is related to integrated graphics. I mentioned the other ffmpeg install as proof I was able to get it working, but then I undid that part and used your instructions alone. I confirmed all the settings you mentioned were set in firefox `about:config` and attempted both the config file and the run-firefox file.

> Hi again... Did you get HW acceleration working using the 3rd-party bundle? Is the reason the LD_LIBRARY_PATH needs to be set in the Firefox configuration or run script? I see, I will push an update.

Correct, I did get it working using your instructions in combination with Clear Fraction's `codecs-cuda` package.

Output from `ldd /usr/lib64/dri/nvidia_drv_video.so`

```bash
        linux-vdso.so.1 (0x00007ffca6d2b000)
        libgstcodecparsers-1.0.so.0 => /usr/lib64/libgstcodecparsers-1.0.so.0 (0x00007f99a8ad8000)
        libEGL.so.1 => /opt/nvidia/lib64/libEGL.so.1 (0x00007f99a8800000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f99a8602000)
        libgstbase-1.0.so.0 => /usr/lib64/libgstbase-1.0.so.0 (0x00007f99a8a24000)
        libgstreamer-1.0.so.0 => /usr/lib64/libgstreamer-1.0.so.0 (0x00007f99a8458000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f99a82b4000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007f99a81cc000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f99a8a1f000)
        libGLdispatch.so.0 => /opt/nvidia/lib64/libGLdispatch.so.0 (0x00007f99a7e00000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f99a8b99000)
        libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007f99a8148000)
        libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 (0x00007f99a8134000)
        libpcre2-8.so.0 => /usr/lib64/libpcre2-8.so.0 (0x00007f99a7d64000)
        libffi.so.7 => /usr/lib64/libffi.so.7 (0x00007f99a8127000)
```

Output from `ls -l /usr/lib64/dri`

```bash
total 470904
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 crocus_dri.so
-rwxr-xr-x  1 root root  4847504 Oct 30  2020 hybrid_drv_video.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 i915_dri.so
-rwxr-xr-x  2 root root  8737168 Feb  1  2019 i965_drv_video.so
-rwxr-xr-x  1 root root 41685496 Nov  2 08:53 iHD_drv_video.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 iris_dri.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 kms_swrast_dri.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 nouveau_dri.so
-rwxr-xr-x  8 root root 13717688 Feb  1  2019 nouveau_drv_video.so
lrwxrwxrwx  1 root root       69 Jan 19 22:06 nvdec_drv_video.so -> /opt/3rd-party/bundles/clearfraction/usr/lib64/dri/nvdec_drv_video.so
lrwxrwxrwx  1 root root       18 Jan 19 22:06 nvidia_drv_video.so -> nvdec_drv_video.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 r300_dri.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 r600_dri.so
-rwxr-xr-x  8 root root 13717688 Feb  1  2019 r600_drv_video.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 radeonsi_dri.so
-rwxr-xr-x  8 root root 13717688 Feb  1  2019 radeonsi_drv_video.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 swrast_dri.so
lrwxrwxrwx  1 root root       69 Jan 19 22:06 vdpau_drv_video.so -> /opt/3rd-party/bundles/clearfraction/usr/lib64/dri/vdpau_drv_video.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 virtio_gpu_dri.so
-rwxr-xr-x  8 root root 13717688 Feb  1  2019 virtio_gpu_drv_video.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 vmwgfx_dri.so
-rwxr-xr-x 24 root root 30999392 Feb  1  2019 zink_dri.so
```

**Comment by marioroy** [comment]
> Correct, I did get it working using your instructions in combination with Clear Fraction's codecs-cuda package.

That's great! The output from the commands look correct. I made an update earlier, adding the extra paths to LD_LIBRARY_PATH. Thank you, for the report.

**Comment by asreich** [comment]
> That's great! The output from the commands look correct. I made an update earlier, adding the extra paths to LD_LIBRARY_PATH. Thank you, for the report.

Awesome, glad this made sense and you were able to confirm on your side. I wasn't sure whether this was expected behavior or not or if I missed something :smile: Thanks for the quick update.
