### ISSUE TITLE
nvidia DRM KMS module name.

### ISSUE THREAD

**Issue by RussianE39** [marioroy/nvidia-driver-on-clear-linux#3]
According to Chapter 36 (https://download.nvidia.com/XFree86/Linux-x86_64/515.43.04/README/kms.html), seems like module name is nvidia_drm, but in pre-install-driver script its called nvidia-drm (/etc/kernel/cmdline.d/nvidia-drm.conf).

**Comment by marioroy** [comment]
Thank you for the report. I updated the content in two files to match the actual driver name; nvidia_drm.modeset=1 and nvidia_uvm in /etc/kernel/cmdline.d/nvidia-drm.conf and /etc/modprobe.d/nvidia-uvm.conf, respectively.

Run `git pull` and `bash pre-install-driver update` to refresh /etc configuration.
