### ISSUE TITLE
Black screen after driver installation with a non blinking cursor at the top left.

### ISSUE THREAD

**Issue by wajirah** [marioroy/nvidia-driver-on-clear-linux#4]
Many thanks for @marioroy for making the NVIDIA driver installation in Clear Linux a breeze. I am stuck with a Black screen after installation with a non blinking cursor at the top left with 38270 version of clear linux with IBT=off. Multi-user.target is fine and I can SSH too. Interestingly, stablediffusion rendering is fine when I access the web interface from the laptop. I am a newbie to linux. Arch linux and Ubuntu installs fine with the desktop but I like the snappiness of clear linux.

It would be great to get the displays working and hope you could help. My hardware- Intel 13th Gen Intel® Core™ i9-13900K, ASUS ROG MAXIMUS Z790 APEX, NVIDIA GeForce RTX™ 4090 with three displays connected, linux installation on a SATA SSD-Resizable Bar ON and Intel Rapid Storage Technology ON.

**Comment by marioroy** [comment]
I pushed an update. It may help resolve the issue.
```bash
git pull
bash pre-install-driver update  # refresh /etc confs 
bash pre-install-driver         # reboot afterwards
bash install-driver latest
```

**Comment by marioroy** [comment]
You're right. This no longer works with recent Clear Linux. I'm taking the repo offline.
